FROM spring-scs-docker-virtual.usw1.packages.broadcom.com/springio/concourse-release-scripts:0.4.2-SNAPSHOT

ADD https://raw.githubusercontent.com/spring-io/concourse-java-scripts/v0.0.4/concourse-java.sh /opt/

