---
platform: linux

inputs:
  - name: src
  - name: artifactory

outputs:
  - name: version

params:
  RELEASE_TYPE:
  ARTIFACTORY_URL: https://((broadcom-jfrog-artifactory/host))/artifactory
  ARTIFACTORY_PROJECT: ((broadcom-jfrog-artifactory/project))
  ARTIFACTORY_USERNAME: ((broadcom-jfrog-artifactory/robot-account.username))
  ARTIFACTORY_PASSWORD: ((broadcom-jfrog-artifactory/robot-account.password))
  ARTIFACTORY_REPOSITORY_STAGING: spring-enterprise-maven-stage-local
  ARTIFACTORY_REPOSITORY_MILESTONE: spring-enterprise-maven-prod-local
  ARTIFACTORY_REPOSITORY_RELEASE_CANDIDATE: spring-enterprise-maven-prod-local
  ARTIFACTORY_REPOSITORY_RELEASE: spring-enterprise-maven-prod-local

run:
  path: src/ci/scripts/promote.sh
