---
aliases:
  - &slack-failure-notification
    put: alert
    params:
      icon_emoji: ":animal-1252:"
      username: concourse
      channel: ((scs-slack-failure-channel))
      text: <!here> Build <${ATC_EXTERNAL_URL}/builds/$BUILD_ID|$BUILD_NAME> of job $BUILD_JOB_NAME in the $BUILD_PIPELINE_NAME pipeline has failed!

jobs:
  - name: build-ci-images
    plan:
      - get: ci-images-git-repo
        trigger: true
      - put: scs-starters-ci-image
        params:
          build: ci-images-git-repo/ci/images/scs-starters-ci
        get_params:
          skip_download: "true"

  - name: build
    serial: true
    public: true
    plan:
    - get: git-repo
      trigger: true
    - task: build-project
      file: git-repo/ci/tasks/build-project.yml
      params:
        ARTIFACTORY_USERNAME: ((scs-artifactory-username))
        ARTIFACTORY_PASSWORD: ((scs-artifactory-password))
    - put: artifactory-repo
      params: &artifactory-params
        signing_key: ((signing-key))
        signing_passphrase: ((signing-passphrase))
        repo: libs-snapshot-local
        folder: distribution-repository
        build_uri: "${ATC_EXTERNAL_URL}/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
        build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
        disable_checksum_uploads: true
    on_failure:
      *slack-failure-notification

  - name: stage-milestone
    serial: true
    plan:
      - get: git-repo
        passed: [build]
      - task: stage
        file: git-repo/ci/tasks/stage.yml
        params:
          RELEASE_TYPE: M
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo-staging
        params:
          repository: stage-git-repo

  - name: stage-rc
    serial: true
    plan:
      - get: git-repo
        passed: [build]
      - task: stage
        file: git-repo/ci/tasks/stage.yml
        params:
          RELEASE_TYPE: RC
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo-staging
        params:
          repository: stage-git-repo

  - name: stage-release
    serial: true
    plan:
      - get: git-repo
        passed: [build]
      - task: stage
        file: git-repo/ci/tasks/stage.yml
        params:
          RELEASE_TYPE: RELEASE
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo-staging
        params:
          repository: stage-git-repo

  - name: promote-milestone
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [stage-milestone]
        params:
          save_build_info: true
      - task: promote
        file: git-repo/ci/tasks/promote.yml
        params:
          RELEASE_TYPE: M
          ARTIFACTORY_SERVER: ((artifactory-server))
          ARTIFACTORY_USERNAME: ((scs-artifactory-username))
          ARTIFACTORY_PASSWORD: ((scs-artifactory-password))

  - name: promote-rc
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [stage-rc]
        params:
          save_build_info: true
      - task: promote
        file: git-repo/ci/tasks/promote.yml
        params:
          RELEASE_TYPE: RC
          ARTIFACTORY_SERVER: ((artifactory-server))
          ARTIFACTORY_USERNAME: ((scs-artifactory-username))
          ARTIFACTORY_PASSWORD: ((scs-artifactory-password))

  - name: promote-release
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [stage-release]
        params:
          save_build_info: true
      - task: promote
        file: git-repo/ci/tasks/promote.yml
        params:
          RELEASE_TYPE: RELEASE
          ARTIFACTORY_SERVER: ((artifactory-server))
          ARTIFACTORY_USERNAME: ((scs-artifactory-username))
          ARTIFACTORY_PASSWORD: ((scs-artifactory-password))

  - name: sync-to-maven-central
    serial: true
    plan:
      - in_parallel:
        - get: git-repo
        - get: artifactory-repo
          passed: [promote-release]
          params:
            save_build_info: true
      - task: sync-to-maven-central
        file: git-repo/ci/tasks/sync-to-maven-central.yml
        params:
          SONATYPE_URL: ((sonatype-url))
          SONATYPE_USERNAME: ((sonatype-user-token))
          SONATYPE_PASSWORD: ((sonatype-user-token-password))
          SONATYPE_STAGING_PROFILE_ID: ((sonatype-staging-profile-id))

resource_types:
  - name: artifactory-resource
    type: registry-image
    source:
      repository: ((dockerhub-mirror-registry))/springio/artifactory-resource
      tag: 0.0.14

  - name: slack-notification
    type: registry-image
    source:
      repository: ((dockerhub-mirror-registry))/cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: git-repo
    type: git
    source:
      uri: ((github-repo))
      username: ((github-username))
      password: ((github-password))
      branch: ((branch))
      ignore_paths: ["ci/images/*"]
      fetch_tags: true

  - name: git-repo-staging
    type: git
    source:
      uri: ((github-repo))
      username: ((github-username))
      password: ((github-password))
      branch: ((github-username))/staging

  - name: ci-images-git-repo
    type: git
    source:
      uri: ((github-repo))
      branch: ((branch))
      paths: ["ci/images/*"]

  - name: scs-starters-ci-image
    type: docker-image
    source:
      repository: ((corporate-harbor-registry))/((docker-hub-organization))/scs-starters-ci
      username: ((corporate-harbor-robot-account.username))
      password: ((corporate-harbor-robot-account.password))

  - name: artifactory-repo
    type: artifactory-resource
    source:
      uri: ((artifactory-server))
      username: ((scs-artifactory-username))
      password: ((scs-artifactory-password))
      build_name: ((build-name))

  - name: alert
    type: slack-notification
    source:
      url: ((scs-slack-webhook))

groups:
  - name: "build"
    jobs:
      - build
  - name: "milestone"
    jobs:
      - stage-milestone
      - promote-milestone
  - name: "rc"
    jobs:
      - stage-rc
      - promote-rc
  - name: "release"
    jobs:
      - stage-release
      - promote-release
      - sync-to-maven-central
  - name: "ci-images"
    jobs:
      - build-ci-images
