---
aliases:
  - &slack-failure-notification
    put: alert
    params:
      icon_emoji: ":animal:"
      username: concourse
      channel: {{scs-slack-failure-channel}}
      text: <!here> Build <${ATC_EXTERNAL_URL}/builds/$BUILD_ID|$BUILD_NAME> of job $BUILD_JOB_NAME in the $BUILD_PIPELINE_NAME pipeline has failed!

jobs:
  - name: build
    serial: true
    public: true
    plan:
    - get: git-repo
      trigger: true
    - get: task-image
    - do:
      - task: build-project
        file: git-repo/ci/tasks/build-project.yml
        image: task-image
        params:
          ARTIFACTORY_USERNAME: ((scs-artifactory-username))
          ARTIFACTORY_PASSWORD: ((scs-artifactory-password))
    - put: artifactory-repo
      params: &artifactory-params
        repo: libs-snapshot-local
        folder: distribution-repository
        build_uri: "${ATC_EXTERNAL_URL}/teams/spring-cloud-services/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
        build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
        disable_checksum_uploads: true
    on_failure:
      *slack-failure-notification

  - name: stage-milestone
    serial: true
    plan:
      - get: git-repo
      - get: task-image
      - task: stage
        file: git-repo/ci/tasks/stage.yml
        image: task-image
        params:
          RELEASE_TYPE: M
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo
        params:
          repository: stage-git-repo
  - name: stage-rc
    serial: true
    plan:
      - get: git-repo
      - get: task-image
      - task: stage
        file: git-repo/ci/tasks/stage.yml
        image: task-image
        params:
          RELEASE_TYPE: RC
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo
        params:
          repository: stage-git-repo
  - name: stage-release
    serial: true
    plan:
      - get: git-repo
      - get: task-image
      - task: stage
        file: git-repo/ci/tasks/stage.yml
        image: task-image
        params:
          RELEASE_TYPE: RELEASE
      - put: artifactory-repo
        params:
          <<: *artifactory-params
          repo: libs-staging-local
      - put: git-repo
        params:
          repository: stage-git-repo
  - name: promote-milestone
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [stage-milestone]
        params:
          save_build_info: true
      - get: task-image
      - task: promote
        file: git-repo/ci/tasks/promote.yml
        image: task-image
        params:
          RELEASE_TYPE: M
          ARTIFACTORY_SERVER: ((artifactory-server))
          ARTIFACTORY_USERNAME: ((scs-artifactory-username))
          ARTIFACTORY_PASSWORD: ((scs-artifactory-password))
  - name: promote-rc
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [stage-rc]
        params:
          save_build_info: true
      - get: task-image
      - task: promote
        file: git-repo/ci/tasks/promote.yml
        image: task-image
        params:
          RELEASE_TYPE: RC
          ARTIFACTORY_SERVER: ((artifactory-server))
          ARTIFACTORY_USERNAME: ((scs-artifactory-username))
          ARTIFACTORY_PASSWORD: ((scs-artifactory-password))
  - name: promote-release
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [stage-release]
        params:
          save_build_info: true
      - get: task-image
      - task: promote
        file: git-repo/ci/tasks/promote.yml
        image: task-image
        params:
          RELEASE_TYPE: RELEASE
          ARTIFACTORY_SERVER: ((artifactory-server))
          ARTIFACTORY_USERNAME: ((scs-artifactory-username))
          ARTIFACTORY_PASSWORD: ((scs-artifactory-password))
  - name: distribute-release
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [promote-release]
        params:
          save_build_info: true
      - get: task-image
      - task: distribute
        file: git-repo/ci/tasks/distribute.yml
        image: task-image
        params:
          ARTIFACTORY_SERVER: ((artifactory-server))
          ARTIFACTORY_USERNAME: ((scs-artifactory-username))
          ARTIFACTORY_PASSWORD: ((scs-artifactory-password))
          BINTRAY_SUBJECT: ((bintray-subject))
          BINTRAY_REPO: ((bintray-repo))
          BINTRAY_USERNAME: ((bintray-username))
          BINTRAY_API_KEY: ((bintray-api-key))
          BINTRAY_PACKAGE: ((bintray-package))
          BINTRAY_DISTRIBUTION_REPO: ((bintray-distribution-repo))
  - name: sync-to-maven-central
    serial: true
    plan:
      - get: git-repo
      - get: artifactory-repo
        passed: [distribute-release]
        params:
          save_build_info: true
      - get: task-image
      - task: sync-to-maven-central
        file: git-repo/ci/tasks/sync-to-maven-central.yml
        params:
          BINTRAY_REPO: ((bintray-repo))
          BINTRAY_SUBJECT: ((bintray-subject))
          BINTRAY_USERNAME: ((bintray-username))
          BINTRAY_API_KEY: ((bintray-api-key))
          BINTRAY_PACKAGE: ((bintray-package))
          SONATYPE_USER_TOKEN: ((sonatype-user-token))
          SONATYPE_PASSWORD_TOKEN: ((sonatype-user-token-password))

resource_types:
  - name: artifactory-resource
    type: docker-image
    source:
      repository: ((dockerhub-mirror-registry))/springio/artifactory-resource
      tag: 0.0.7
  - name: slack-notification
    type: docker-image
    source:
      repository: ((dockerhub-mirror-registry))/cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: git-repo
    type: git
    source:
      uri: ((github-repo))
      username: ((github-username))
      password: ((github-password))
      branch: ((branch))
      ignore_paths: ["ci/images/*"]
  - name: artifactory-repo
    type: artifactory-resource
    source:
      uri: ((artifactory-server))
      username: ((scs-artifactory-username))
      password: ((scs-artifactory-password))
      build_name: ((build-name))
  - name: alert
    type: slack-notification
    source:
      url: ((scs-slack-webhook))
  - name: task-image
    type: registry-image
    source:
      repository: ((dockerhub-mirror-registry))/((docker-hub-organization))/release-ci-image
      tag: ((branch))
groups:
  - name: "build"
    jobs: ["build"]
  - name: "release"
    jobs: ["stage-milestone", "stage-rc", "stage-release", "promote-milestone", "promote-rc", "promote-release", "distribute-release", "sync-to-maven-central"]
