---
aliases:
  - &failure-notification
    put: notify
    inputs: detect
    no_get: true
    params:
      alert_type: failed
      message: SCS Starters (4.3.x)
  - &artifactory-params
    signing_key: ((broadcom-jfrog-artifactory/signing.key))
    signing_passphrase: ((broadcom-jfrog-artifactory/signing.passphrase))
    folder: distribution-repository
    build_uri: "${ATC_EXTERNAL_URL}/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
    build_number: "${BUILD_PIPELINE_NAME}-${BUILD_JOB_NAME}-${BUILD_NAME}"
    disable_checksum_uploads: true

jobs:
  - name: build-ci-images
    plan:
      - in_parallel:
          - get: ci-images-src
            trigger: true
          - get: oci-build-task-image
          - get: alpine-image
      - task: docker-config
        image: alpine-image
        config:
          platform: linux
          outputs:
            - name: docker-config
          params:
            DOCKER_CONFIG_JSON: ((broadcom-jfrog-artifactory/dockerconfig))
          run:
            path: sh
            args:
              - -exc
              - |
                echo "$DOCKER_CONFIG_JSON" > docker-config/config.json
      - task: build
        image: oci-build-task-image
        privileged: true
        config:
          platform: linux
          inputs:
            - name: ci-images-src
            - name: docker-config
          outputs:
            - name: image
          params:
            CONTEXT: ci-images-src/ci/images/scs-starters-ci
            DOCKER_CONFIG: docker-config
          run:
            path: build
      - put: ci-image
        inputs: detect
        params:
          image: image/image.tar
        get_params:
          skip_download: true
    on_failure: *failure-notification

  - name: build
    serial: true
    public: true
    plan:
      - in_parallel:
          - get: src
            trigger: true
          - get: ci-image
      - task: build-project
        image: ci-image
        file: src/ci/tasks/build-project.yml
      - put: artifactory
        params:
          <<: *artifactory-params
          repo: spring-enterprise-maven-dev-local
    on_failure: *failure-notification

  - name: renovate
    plan:
      - in_parallel:
          - get: src
          - get: weekly
            trigger: true
          - get: renovate-image
      - task: renovate
        image: renovate-image
        file: src/ci/tasks/renovate.yml
    on_failure: *failure-notification

  - name: stage-milestone
    serial: true
    plan:
      - in_parallel:
          - get: src
            passed: [build]
          - get: ci-image
      - task: stage
        image: ci-image
        file: src/ci/tasks/stage.yml
        params:
          RELEASE_TYPE: M
      - put: artifactory
        params:
          <<: *artifactory-params
          repo: spring-enterprise-maven-stage-local
      - put: staging-src
        params:
          repository: stage-git-repo

  - name: stage-rc
    serial: true
    plan:
      - in_parallel:
          - get: src
            passed: [build]
          - get: ci-image
      - task: stage
        image: ci-image
        file: src/ci/tasks/stage.yml
        params:
          RELEASE_TYPE: RC
      - put: artifactory
        params:
          <<: *artifactory-params
          repo: spring-enterprise-maven-stage-local
      - put: staging-src
        params:
          repository: stage-git-repo

  - name: stage-release
    serial: true
    plan:
      - in_parallel:
          - get: src
            passed: [build]
          - get: ci-image
      - task: stage
        image: ci-image
        file: src/ci/tasks/stage.yml
        params:
          RELEASE_TYPE: RELEASE
      - put: artifactory
        params:
          <<: *artifactory-params
          repo: spring-enterprise-maven-stage-local
      - put: staging-src
        params:
          repository: stage-git-repo

  - name: promote-milestone
    serial: true
    plan:
      - in_parallel:
          - get: src
          - get: artifactory
            passed: [stage-milestone]
            params:
              save_build_info: true
          - get: ci-image
      - task: promote
        image: ci-image
        file: src/ci/tasks/promote.yml
        params:
          RELEASE_TYPE: M

  - name: promote-rc
    serial: true
    plan:
      - in_parallel:
          - get: src
          - get: artifactory
            passed: [stage-rc]
            params:
              save_build_info: true
          - get: ci-image
      - task: promote
        image: ci-image
        file: src/ci/tasks/promote.yml
        params:
          RELEASE_TYPE: RC

  - name: promote-release
    serial: true
    plan:
      - in_parallel:
          - get: src
          - get: artifactory
            passed: [stage-release]
            params:
              save_build_info: true
          - get: ci-image
      - task: promote
        image: ci-image
        file: src/ci/tasks/promote.yml
        params:
          RELEASE_TYPE: RELEASE

  - name: sync-to-maven-central
    serial: true
    plan:
      - in_parallel:
          - get: src
          - get: artifactory
            passed: [promote-release]
            params:
              save_build_info: true
          - get: ci-image
      - task: sync-to-maven-central
        image: ci-image
        file: src/ci/tasks/sync-to-maven-central.yml

resource_types:
  - name: artifactory-resource
    type: registry-image
    source:
      repository: spring-scs-docker-virtual.((broadcom-jfrog-artifactory/host))/springio/artifactory-resource
      username: ((broadcom-jfrog-artifactory/robot-account.username))
      password: ((broadcom-jfrog-artifactory/robot-account.password))
      tag: 0.0.19

  - name: notify-type
    type: registry-image
    source:
      repository: spring-scs-docker-virtual.((broadcom-jfrog-artifactory/host))/epic2/concourse-google-chat-alert-resource
      username: ((broadcom-jfrog-artifactory/robot-account.username))
      password: ((broadcom-jfrog-artifactory/robot-account.password))
      tag: dev

resources:
  - name: src
    type: git
    icon: github
    source:
      uri: https://((github.token))@github.com/pivotal-cf/spring-cloud-services-starters.git
      branch: ((branch))
      ignore_paths: ["ci/images/*"]
      fetch_tags: true

  - name: staging-src
    type: git
    icon: github
    source:
      uri: https://((github.token))@github.com/pivotal-cf/spring-cloud-services-starters.git
      branch: ((github.git-email))/staging-((branch))

  - name: ci-images-src
    type: git
    icon: github
    source:
      uri: https://((github.token))@github.com/pivotal-cf/spring-cloud-services-starters.git
      branch: ((branch))
      paths: ["ci/images/*"]

  - name: ci-image
    type: registry-image
    icon: docker
    source:
      repository: spring-scs-docker-dev-local.((broadcom-jfrog-artifactory/host))/ci/scs-starters
      username: ((broadcom-jfrog-artifactory/robot-account.username))
      password: ((broadcom-jfrog-artifactory/robot-account.password))
      tag: jdk-17

  - name: oci-build-task-image
    type: registry-image
    icon: docker
    source:
      repository: spring-scs-docker-virtual.((broadcom-jfrog-artifactory/host))/concourse/oci-build-task
      username: ((broadcom-jfrog-artifactory/robot-account.username))
      password: ((broadcom-jfrog-artifactory/robot-account.password))
      tag: 0.11.1

  - name: alpine-image
    type: registry-image
    icon: docker
    source:
      repository: spring-scs-docker-virtual.((broadcom-jfrog-artifactory/host))/alpine
      username: ((broadcom-jfrog-artifactory/robot-account.username))
      password: ((broadcom-jfrog-artifactory/robot-account.password))
      tag: 3.19.1

  - name: artifactory
    type: artifactory-resource
    icon: cube-outline
    source:
      uri: https://((broadcom-jfrog-artifactory/host))/artifactory
      username: ((broadcom-jfrog-artifactory/robot-account.username))
      password: ((broadcom-jfrog-artifactory/robot-account.password))
      project: ((broadcom-jfrog-artifactory/project))
      build_name: spring-cloud-services-starters

  - name: weekly
    type: time
    icon: calendar-clock
    source:
      start: 12:00 AM
      stop: 1:00 AM
      days:
        - Friday
      location: America/New_York
      initial_version: true

  - name: renovate-image
    type: registry-image
    source:
      repository: spring-scs-docker-virtual.((broadcom-jfrog-artifactory/host))/renovate/renovate
      username: ((broadcom-jfrog-artifactory/robot-account.username))
      password: ((broadcom-jfrog-artifactory/robot-account.password))
      tag: 39.263.0

  - name: notify
    type: notify-type
    icon: bullhorn
    source:
      url: ((gspace.webhook))

groups:
  - name: "build"
    jobs:
      - build
      - renovate
  - name: "milestone"
    jobs:
      - stage-milestone
      - promote-milestone
  - name: "rc"
    jobs:
      - stage-rc
      - promote-rc
  - name: "release"
    jobs:
      - stage-release
      - promote-release
      - sync-to-maven-central
  - name: "ci-images"
    jobs:
      - build-ci-images
